//Cart Types
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'; // Add this line

//Login Types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE ='LOGIN_FAILURE';

//logout Type
export const LOGOUT = 'LOGOUT';

//show-box type
export const SHOW_MESSAGE_BOX = 'SHOW_MESSAGE_BOX';
export const HIDE_MESSAGE_BOX = 'HIDE_MESSAGE_BOX';


//user profile action Types
export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_FAILURE';
export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_SUCESS = 'UPDATE_USER_PROFILE_SUCESS';
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE';



// actionTypes.ts
export const FETCH_WISHLISTS_REQUEST = 'FETCH_WISHLISTS_REQUEST';
export const FETCH_WISHLISTS_SUCCESS = 'FETCH_WISHLISTS_SUCCESS';
export const FETCH_WISHLISTS_FAILURE = 'FETCH_WISHLISTS_FAILURE';

export const ADD_WISHLIST_REQUEST = 'ADD_WISHLIST_REQUEST';
export const ADD_WISHLIST_SUCCESS = 'ADD_WISHLIST_SUCCESS';
export const ADD_WISHLIST_FAILURE = 'ADD_WISHLIST_FAILURE';

export const DELETE_WISHLIST_REQUEST = 'DELETE_WISHLIST_REQUEST';
export const DELETE_WISHLIST_SUCCESS = 'DELETE_WISHLIST_SUCCESS';
export const DELETE_WISHLIST_FAILURE = 'DELETE_WISHLIST_FAILURE';

